secrets:
  db_password_file:
    file: ./db_password.secret
  redis_password_file:
    file: ./redis_password.secret

services:
  api:
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    image: ghcr.io/mxhdiqaim/kantisoft-api:latest
    pull_policy: always
    container_name: kantisoft-api-prod
    #    env_file:
    #      - .env.prod
    environment:
      DB_PASSWORD_FILE_PATH: /run/secrets/db_password_file
      REDIS_PASSWORD_FILE_PATH: /run/secrets/redis_password_file
      NODE_ENV: production
      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    secrets:
      - db_password_file
      - redis_password_file

  postgres_db:
    image: postgres:16-alpine
    container_name: kantisoft-db-prod
    #    env_file:
    #      - .env.prod
    environment:
      # These variables must be defined in your .env.prod file!
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password_file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    secrets:
      - db_password_file
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis_cache:
    image: redis:8-alpine
    container_name: kantisoft-redis-prod
    #    env_file:
    #      - .env.prod
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password_file
    command: redis-server --appendonly yes --requirepass /run/secrets/redis_password_file --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$(cat /run/secrets/redis_password_file)", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
    volumes:
      - redis_data_prod:/data
    secrets:
      - redis_password_file

  nginx:
    image: nginx:stable-alpine
    container_name: kantisoft-nginx-prod
    #    env_file:
    #      - .env.prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount custom configuration file
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

      # Mount the snippets directory
      - ./nginx/snippets:/etc/nginx/snippets:ro
      
      # Volume for SSL certificates
      - certbot_volumes:/etc/letsencrypt
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: kantisoft-certbot-prod
    # Mount same volumes as Nginx
    volumes:
      - certbot_volumes:/etc/letsencrypt
      # Mount the volume Nginx uses for the ACME challenge
      - certbot_volumes_www:/var/www/certbot
    # The command runs once to attempt renewal and then exits
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'"


volumes:
  postgres_data_prod:
  redis_data_prod:
  certbot_volumes:
  certbot_volumes_www: