secrets:
  db_password_file:
    file: ./db_password.secret
  redis_password_file:
    file: ./redis_password.secret

services:
  api:
    image: ghcr.io/mxhdiqaim/kantisoft-api:latest
    pull_policy: always
    container_name: kantisoft-api-prod
    ports:
      - 5473:5473
    environment:
      NODE_ENV: production
      PORT: ${PORT:-5473}

      # Database Settings
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_SSL_REQUIRED: ${DB_SSL_REQUIRED:-false}
      DB_PASSWORD_FILE: /run/secrets/db_password_file

      # Application Settings
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}

      APP_URL: ${APP_URL:-app.kantisoft.com}
      LANDING_PAGE: ${LANDING_PAGE:-kantisoft.com}
      SENTRY_DSN: ${SENTRY_DSN}

      # Redis Settings
      REDIS_PORT: 6379
      REDIS_HOST: redis_cache
      REDIS_PASSWORD_FILE: /run/secrets/redis_password_file
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    secrets:
      - db_password_file
      - redis_password_file
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5473/api/v1/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres_db:
    image: postgres:16-alpine
    container_name: kantisoft-db-prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password_file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    secrets:
      - db_password_file
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis_cache:
    image: redis:8-alpine
    container_name: kantisoft-redis-prod
    command: sh -c 'redis-server /usr/local/etc/redis/redis.conf --requirepass "$$(cat /run/secrets/redis_password_file)"'
    volumes:
      - redis_data_prod:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    secrets:
      - redis_password_file
    healthcheck:
      test: |
        sh -c 'redis-cli -a "$$(cat /run/secrets/redis_password_file)" ping | grep -q PONG'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


volumes:
  postgres_data_prod:
  redis_data_prod:
#  certbot_volumes:
#  certbot_volumes_www: