version: "3.8"

secrets:
  db_password_file:
    file: ./db_password.secret
  redis_password_file:
    file: ./redis_password.secret

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kantisoft-api-prod
    env_file:
      - .env.prod
    #    ports:
    #      - "5473:5473"
    environment:
      DB_PASSWORD_FILE_PATH: /run/secrets/db_password_file
      REDIS_PASSWORD_FILE_PATH: /run/secrets/redis_password_file
      NODE_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      REDIS_HOST: redis_cache
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    secrets:
      - db_password_file
      - redis_password_file

  postgres_db:
    image: postgres:16-alpine
    container_name: kantisoft-db-prod
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      #      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password_file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    secrets:
      - db_password_file

  redis_cache:
    image: redis:8-alpine
    container_name: kantisoft-redis-prod
    env_file:
      - .env.prod
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password_file
    #      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s
    volumes:
      - redis_data_prod:/data
    secrets:
      - redis_password_file

  nginx:
    image: nginx:stable-alpine
    container_name: kantisoft-nginx-prod
    env_file:
      - .env.prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount custom configuration file
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Volume for SSL certificates (must be persistent)
      - certbot_volumes:/etc/letsencrypt
    depends_on:
      - api

volumes:
  postgres_data_prod:
  redis_data_prod:
  certbot_volumes: