name: CD - Build and Push Docker Image

on:
  push:
    branches:
      - master # Only run the CD job when code is pushed/merged to the master branch

env:
  REGISTRY: ghcr.io # GitHub Container Registry
  IMAGE_NAME: ${{ github.repository }} # e.g., mxhdiqaim/kantisoft-api

jobs:
  build-and-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest

    # This should be a name of CI workflow 'build-and-test' for this to work
    needs: build-and-test

    permissions:
      contents: read
      packages: write # Necessary to push to GHCR

    steps:
      - name: ‚¨áÔ∏è Checkout Repository
        uses: actions/checkout@v4

      - name: üè∑Ô∏è Extract Metadata (Tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api
          tags: |
            type=sha,format=short, prefix=sha- # Tag image with the full commit SHA (e.g., :838b973...)
            type=raw,value=latest,enable=true # Also tag with :latest

      - name: üîë Docker Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: üõ† Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üèóÔ∏è Build and Push Production Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
